### ISSUE TITLE
nub-context action getters

### ISSUE THREAD

**Issue by chase-moskal** [benevolent-games/nubs#15]
- we need the nub-context to provide a special object called `actions` which allows consumer applications to query at any moment what was the last state of a given action input

for example

```ts
const nubContext = document.querySelector<NubContext>("nub-context")

renderLoop.add(() => {

  // detect if a key is currently pressed
  if (nubContext.actions.forward.pressed)
    console.log("move forward!")
  else
    console.log("do not move forward")

  // get the current vector of a stick
  const {vector} = nubContext.actions.lookstick
})
```

- nub-context needs to somehow expose this magical `actions` object as a property

**Comment by chase-moskal** [comment]
- you may need to badger @chase-moskal to get him to add an magical `use.initialize` that runs in-constructor so we can make `actions` instantly available

**Comment by chase-moskal** [comment]
![Image](https://user-images.githubusercontent.com/7145590/202816065-bafede34-b98f-4e11-b93c-079d1b28dcb8.png)

**Comment by chase-moskal** [comment]
@PaulAroo i've implemented this feature on `master`

**Comment by PaulAroo** [comment]
Thanks @chase-moskal👍
