### ISSUE TITLE
⌨️ bindings editor

### ISSUE THREAD

**Issue by chase-moskal** [benevolent-games/nubs#9]
- new component
- salvage code from gridboard if possible

**Comment by chase-moskal** [comment]
![Image](https://user-images.githubusercontent.com/7145590/202812008-e7bf4557-6bcc-4285-af2e-7649dcc0c34f.png)

**Comment by chase-moskal** [comment]
- nub input type `Key` will require a special "key input grabber component"
- likewise, nub input `Vector2` will also require its own special "stick input grabber component"

**Comment by chase-moskal** [comment]
![Image](https://user-images.githubusercontent.com/7145590/202812274-d3952c94-d714-496d-baff-f231a1f2dfbf.png)

**Comment by chase-moskal** [comment]
![image](https://user-images.githubusercontent.com/7145590/202868809-48ba127b-8cb6-4e67-ab3f-67763ca493f1.png)

**Comment by chase-moskal** [comment]
work in progress has been merged to master

as seen in this comment https://github.com/benevolent-games/nubs/pull/17#pullrequestreview-1190699784

we need to fix this bug:
1. after i rebind an action to a new key
1. the new key isn't triggering the action (it should)

**Comment by zenkyuv** [comment]
> work in progress has been merged to master
> 
> as seen in this comment https://github.com/benevolent-games/nubs/pull/17#pullrequestreview-1190699784
> 
> we need to fix this bug:
> 1. after i rebind an action to a new key
> 1. the new key isn't triggering the action (it should)

Yeah i just didnt get that into account ..

**Comment by chase-moskal** [comment]
@zenkyuv cool, no worries, once we have that last aspect implemented, we'll close this ticket
